import { saveAs } from 'file-saver';
import { EconomicLossReport } from './types';
import { formatReportFilename } from './reportSnapshot';

/**
 * Export the full report snapshot as a JSON file
 */
export function exportReportToJson(report: EconomicLossReport): void {
  const jsonString = JSON.stringify(report, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json;charset=utf-8;' });
  const filename = formatReportFilename(
    'Economic-Report',
    report.assumptions.caseInfo.plaintiff,
    undefined,
    'json'
  );
  saveAs(blob, filename);
}

/**
 * Copy report summary to clipboard
 */
export async function copyReportSummaryToClipboard(report: EconomicLossReport): Promise<void> {
  const { assumptions, results, metadata } = report;
  const { caseInfo } = assumptions;
  const { summaryMetrics, scenarioProjections } = results;

  const fmtUSD = (n: number) => 
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);

  const activeScenario = scenarioProjections.find(s => s.id === metadata.activeScenario);

  const summary = `
ECONOMIC LOSS APPRAISAL SUMMARY
================================
Plaintiff: ${caseInfo.plaintiff}
Report Date: ${new Date(caseInfo.reportDate).toLocaleDateString()}
Report ID: ${metadata.reportId}

DAMAGE SUMMARY
--------------
Past Loss: ${fmtUSD(summaryMetrics.totalPastLoss)}
Future Earnings (PV): ${fmtUSD(summaryMetrics.totalFuturePV)}
Total Earnings Loss: ${fmtUSD(summaryMetrics.totalEarningsLoss)}
Household Services (PV): ${fmtUSD(summaryMetrics.householdServicesPV)}
Life Care Plan (PV): ${fmtUSD(summaryMetrics.lifeCareplanPV)}
--------------------------------
GRAND TOTAL: ${fmtUSD(summaryMetrics.grandTotal)}

ACTIVE SCENARIO
---------------
${activeScenario?.label || 'N/A'}
Retirement Age: ${activeScenario?.retirementAge.toFixed(1) || 'N/A'}
YFS: ${activeScenario?.yfs.toFixed(2) || 'N/A'} years
WLF: ${activeScenario?.wlfPercent.toFixed(2) || 'N/A'}%

Generated by ForensicSuite v${metadata.appVersion}
${metadata.generatedAt}
`.trim();

  await navigator.clipboard.writeText(summary);
}
